### ISSUE TITLE
Reorder the games such that users love it more

### ISSUE THREAD

**Issue by aryamangodara** [aryamangodara/Arcade-Plaza#6]

**Comment by AKhatabdev** [comment]
Hello,

I would like to work on this issue, could you please provide more information.

Kind regards

**Comment by aryamangodara** [comment]
> Hello,
> 
> I would like to work on this issue, could you please provide more information.
> 
> Kind regards

Hi,
Please download android app and play the games from it ...
The games from the company 'gamezop' should be placed at the bottom and
you can easily judge the better games and place them on the top 😉

**Comment by AKhatabdev** [comment]
Hello,

I won't be working on this issue.

Kind regards
