### ISSUE TITLE
When we click on the search button...

### ISSUE THREAD

**Issue by aryamangodara** [aryamangodara/Arcade-Plaza#8]
- keyboard should automatically appear 
- search should be Realtime i.e. the letters we are writing should be simultaneously correspond to the list of games that will appear in screen body
- when no game is found our users must see "No game found" in screen's body 
- after clicking the cross button keyboard should go back too

**Comment by aryamangodara** [comment]
@samitkapoor can you have a look 👀

**Comment by samitkapoor** [comment]
@aryamangodara Yeah, sure ill take a look in my free time

**Comment by samitkapoor** [comment]
@aryamangodara I have solved this issue and made a corresponding pull request.
